services:
  - type: web
    name: richmenu-id
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python richid.py
    plan: free
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        value: ""
