services:
  - type: worker
    name: richmenu-id
    env: python
    buildCommand: ""
    startCommand: python delete_all.py
    plan: free
    envVars:
      - key: LINE_CHANNEL_ACCESS_TOKEN
        value: ""
